### ISSUE TITLE
How to start the tool 

### ISSUE THREAD

**Issue by abensim** [baadev/TonUtils#2]
Hi , I'm not familiar with those scripts and I'm a beginner. 
i installed everything and I'm looking for the command to launch the script. 

I'm looking for a feature that can extract the TON address by providing the key , you thing it's possible to add it ? 

thanks a lot for your answer

**Comment by baadev** [comment]
@abensim sorry for the late reply. So you want to get a public wallet address based on a mnemonic? 
It is possible and could be added as next util, probably this weekend.

**Comment by baadev** [comment]
@abensim utility added with ff65aa1 commit
